openapi: '3.0.0'
info:
  version: 1.0.0
  title: Cimshare Documentation
  license:
    name: MIT
servers:
  - url: https://api.cimshare.com/v1
paths:
  /cims:
    get:
      summary: List all CIMs
      operationId: listCims
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of CIMs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cims'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a CIM
      operationId: createCim
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cims/{cimId}:
    get:
      summary: Get CIM details
      operationId: showCimById
      parameters:
        - name: cimId
          in: path
          required: true
          description: The id of the CIM to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cims'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /esignatures:
    get:
      summary: List signatures
      operationId: listSignatures
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of signatures
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signatures'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create signature
      operationId: createSignature
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Cim:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        status:
          type: string
    Cims:
      type: array
      items:
        $ref: '#/components/schemas/Cim'
    Signature:
      required:
        - id
        - signer
      properties:
        id:
          type: integer
          format: int64
        signer:
          type: string
        completed:
          type: boolean
    Signatures:
      type: array
      items:
        $ref: '#/components/schemas/Signature'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string